# Generated by Django 4.0.5 on 2022-06-29 20:33

from django.db import migrations

DEFAULT_CATEGORY = "Uncategorised"


def add_default_category(apps, _):
    category_model = apps.get_model(app_label="blog", model_name="Category")

    category_model.objects.get_or_create(name=DEFAULT_CATEGORY)


def remove_default_category(apps, _):

    category_model = apps.get_model(app_label="blog", model_name="Category")

    category = category_model.objects.filter(name=DEFAULT_CATEGORY).first()

    if category:
        category.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category_post_category"),
    ]

    operations = [migrations.RunPython(add_default_category, remove_default_category)]
