# Generated by Django 4.0.5 on 2022-07-05 20:56

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=blog.models.get_category_id, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='blog.category'),
        ),
    ]
